site_name: SCynergy 2026 - Getting Started with MeluXina
site_description: Tutorial for your first steps on MeluXina supercomputer
site_url: https://LuxProvide.github.io/GettingStartedOnMeluXina
site_author: Xavier Besseron
site_dir: public

nav:
    - 🏠 Overview: index.md
    - 1️⃣ Configuring your access to MeluXina: connections_meluxina.md
    - 2️⃣ Urban wind simulation and visualization: urban_wind_simulation.md
    - 3️⃣ PyTorch notebook with JupyterLab: pytorch_notebook.md

exclude_docs: |
    *.backup

# strict: true
validation:
    omitted_files: warn
    absolute_links: warn
    unrecognized_links: warn

theme:
    #include_homepage_in_sidebar: False
    #navigation_depth: 4
    #collapse_navigation: True
    #titles_only: False
    #sticky_navigation: True
    name: material
    logo: assets/LuxProvide_logo_white.svg
    favicon: assets/favicon.png
    language: en
    features:
        - navigation.expand
        - navigation.footer
        - navigation.sections
        - navigation.path
        - toc.integrate
        - content.code.copy
        - content.code.select
        - content.code.annotate
        #- navigation.tabs

plugins:
    - search
    - progress
    - include-markdown
    - open-in-new-tab
    - glightbox

extra_css:
    - stylesheets/extra.css

markdown_extensions:
    - attr_list
    - md_in_html
    - tables
    - admonition
    - toc:
          permalink: true
    - codehilite:
          guess_lang: true
    - footnotes
    - markdown_include.include:
          base_path: docs
    - markdown.extensions.admonition
    - meta
    - pymdownx.arithmatex:
          generic: true
    - pymdownx.details
    - pymdownx.magiclink:
          repo_url_shorthand: true
          social_url_shorthand: true
    - pymdownx.highlight:
          anchor_linenums: true
          line_spans: __span
          pygments_lang_class: true
    - pymdownx.inlinehilite
    - pymdownx.snippets
    - pymdownx.tabbed
    - pymdownx.smartsymbols
    - pymdownx.tabbed:
          alternate_style: true
    - pymdownx.superfences
    - pymdownx.details
    - pymdownx.keys
    - pymdownx.critic
    - pymdownx.caret
    - pymdownx.keys
    - pymdownx.mark
    - pymdownx.tilde
